### ISSUE TITLE
No images presenting the game in the README

### ISSUE THREAD

**Issue by franpog859** [BartekPog/Go-game#1]
After finishing the implementation please, add some GIF image presenting the game to the `README.md` file. I'd love to star this repository and play with the app but I want to see it first! 😄

**Comment by BartekPog** [comment]
@franpog859 Thanks for attention! That is a great idea! GIF image will definitely be added to readme after deployment (and creation of proper readme file) :D

**Comment by franpog859** [comment]
It would be great if you also add the link to the game in the repository header! There is a place for website right next to the description field 😄 It will make the game access much easier

**Comment by BartekPog** [comment]
Oh right! The website link has been added to the repository header. The issue will stay open because the GIF images are still not present in README. Thank you for participating :D

**Comment by BartekPog** [comment]
The gif image has been added to `README.md` file! With this in mind I consider the issue closed.  I am grateful for the help with making this project better! :smile:
